packages:
  - .

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd

ignoredBuiltDependencies:
  - unrs-resolver

allowBuilds:
  esbuild: true
  sharp: false
  unrs-resolver: false
  workerd: false
